### ISSUE TITLE
bug with new version of vue and bootstrap-vue

### ISSUE THREAD

**Issue by designy** [tinymce/tinymce-vue#106] opened 2019-09-25 06:55 UTC
when we update bootstrap-vue to version 2.0.2, TinyMCE works fine for the first load inside modal, 
![Capture](https://user-images.githubusercontent.com/5834795/65576228-697a3200-df7e-11e9-8047-54d7aef83c40.PNG)

but after a close and open modal, TinyMCE editor disappeared and just text area is shown.
![Capture](https://user-images.githubusercontent.com/5834795/65576290-8ca4e180-df7e-11e9-956c-229d6e080ff2.PNG)

 remove TinyMCE editor and create again whit below commands works but it has a bad experience for the user.

			global.tinymce.EditorManager.execCommand(
				'mceRemoveEditor',
				false,
				'editor-id'
			);
			global.tinymce.EditorManager.execCommand(
				'mceAddEditor',
				false,
				'editor-id'
			);

**Comment by SimonFc** [comment] 2019-09-25 11:14
I think this is due to a common issue with TinyMCE in iframe mode(try inline mode and it'll probably work just fine). Whenever an iframe gets moved/detached from the DOM it'll re-render. This will break TinyMCE and unfortunately there's nothing we can do about it. As of now, it's the user's responsibility to either make sure that doesn't happen or to manually tear down/set up TinyMCE(tinymce-vue) whenever necessary. I'll close this now but let me know if you think the issue is due to something else and I'll re-open it!

**Closed by SimonFc** 2019-09-25 11:14 UTC

**Comment by asika32764** [comment] 2019-12-29 18:36
There is a hack can solve this problem.

https://github.com/tinymce/tinymce-vue/blob/5ed590f32f393a7bb61fee11b4324f7102b00a98/src/main/ts/components/Editor.ts#L84-L86

Modify to:

```js
        if (getTinymce() !== null) {
            setTimeout(() => {
              initialise(this)();
            }, 0);
        }
```

Make tinymce initialise later so that it can render after modal available.

I don't know why nextTick not work here but setTimeout works for me.

Can we add this workaround to core?

**Comment by olivier-nicolas** [comment] 2021-09-07 09:07
Hi regarding this issue I have the same behavior. I found out a workaround without changing the tiny mce wrapper code.

To force the regeneration of the component just use a promise with timeout 
`        const p = new Promise(() => {
          setTimeout(() => {
            uuid.value = uuidv4();
          }, 0);
        });
        p.then();
` 
It was working just fine to me.

**Comment by maxganiev** [comment] 2024-06-13 07:47
> Hi
> 
> Regarding this issue I have the same behavior. I found out a workaround without changing the tiny mce wrapper code.
> 
> To force the regeneration of the component just use a promise with timeout
> 
> ```
> <editor
>   ref="editor"
>   v-model="body"
>   :key="uuid"
> />
> ```
> 
> ```js
> const p = new Promise(() => {
>   setTimeout(() => {
>     uuid.value = uuidv4();
>   }, 0);
> });
> p.then();
> ```
> 
> It was working just fine to me.

or alternative without using uuidv:

![image](https://github.com/tinymce/tinymce-vue/assets/63904631/57e2479d-e5e6-4b75-82fb-79b04044859c)
