### ISSUE TITLE
I set the height and width of tinymce, but it did not succeed.

### ISSUE THREAD

**Issue by munitioner** [tinymce/tinymce-vue#191] opened 2020-10-31 13:07 UTC
There is another problem. I set the height and width of tinymce, but it did not succeed.
my codesandbox project https://codesandbox.io/s/async-surf-srhqk?file=/src/App.vue

**Comment by lnewson** [comment] 2020-10-31 22:32
Closing as a duplicate of https://github.com/tinymce/tinymce/issues/6161

**Closed by lnewson** 2020-10-31 22:32 UTC
