### ISSUE TITLE
Unable to paste image

### ISSUE THREAD

**Issue by techpool** [tinymce/tinymce-vue#3] opened 2018-03-09 05:47 UTC
`paste_data_image` attribute doesn't work and I'm unable to make it work even passing the same property as a part of the init object.

I'm trying the above in Chrome.

**Comment by fyrkant** [comment] 2018-03-09 09:16
Do you mean the paste plugin [`paste_data_images`](https://www.tinymce.com/docs/plugins/paste/#paste_data_images)?

**Comment by techpool** [comment] 2018-03-09 17:07
`paste_data_images` is more like an init option and not a plugin I guess. And I tried passing the same as a part of the init options and also included the `paste` plugin but it seems like it's not working.
Everytime instead of the image the url gets pasted.

**Comment by fyrkant** [comment] 2018-03-12 08:53
No I mean it is an option for the paste plugin, it won't do anything without the plugin activated. But it doesn't work even with the plugin?

**Comment by fyrkant** [comment] 2018-03-12 09:24
@techpool 
Hmm, maybe you are misunderstanding the `paste_data_images` setting? The setting won't change the images with urls to data urls, it only sets if it should be allowed to paste data url images or not. 

Anyway, I am not able to reproduce any problems pasting images with the vue wrapper, I'll need some more info on how to reproduce it to be able to help you.

**Comment by Afraithe** [comment] 2018-05-13 23:32
Not enough feedback, closing.

**Closed by Afraithe** 2018-05-13 23:32 UTC
Labels: question
