### ISSUE TITLE
output-Format reversing text

### ISSUE THREAD

**Issue by chad-l** [tinymce/tinymce-vue#147] opened 2020-05-15 20:59 UTC
`<editor v-model="value1"
                                output-format="text"
                                id="tiny">
                        </editor>`

When output-format="text" is used, the output is reversed. Example "Hello" appears as "olleH" in the tiny doc input and in the property. This only occurs with the two way binding using v-model.

https://codesandbox.io/s/tinymcevue-r5xlq?file=/src/App.vue:309-368

I expect to enter "Hello" and see "Hello" entered into the input box.

**Comment by jscasca** [comment] 2020-05-18 03:22
Hi @chad-l 

Thank for bringing this up. The problem is not the output being reversed but rather the Editor reacting to every change and setting the content back setting the caret back to the start of the document after every key press.

We have a PR with a temporal fix for this issue but we will probably be reviewing the whole `v-model` deal.

What is your use case for having TinyMCE as a controlled component with text?

**Comment by chad-l** [comment] 2020-05-18 14:20
It needs to save to a database as just text. I can't have an HTML element wrapping the text.

**Closed** 2020-05-22 05:52 UTC
