### ISSUE TITLE
plugin for code view, content not editable

### ISSUE THREAD

**Issue by oindypoind** [tinymce/tinymce-vue#93] opened 2019-07-08 14:25 UTC
When adding the plugin for "code" to be able to access the source code, the panel pops up to show the raw HTML for the editor, but it can't be clicked or edited. You can close the panel however.

**Comment by oindypoind** [comment] 2019-07-08 14:59
I think this is actually related to the fact that i'm using the Vuetify framework, and that has assigned an event listener on the Window object which is bound to the textarea, and that's intercepting the focus-in event on the textarea. Just can't work out if that can be stopped from this component.

**Comment by SimonFc** [comment] 2019-07-15 14:36
Are you able to reproduce the issue [here](https://codesandbox.io/s/tinymcevue-lkf49)?

**Comment by oindypoind** [comment] 2019-07-15 14:43
No it seems to work fine there. I think I narrowed it down to explicitly when trying to use tinymce-vue when wrapped in Vuetify's popup window. Vuetify seems to be stealing the focus events via code attached to the page as a whole.

**Comment by SimonFc** [comment] 2019-07-15 14:54
Ah okay, sounds like it's not a bug with tinymce-vue then. I'll close this issue now but if you find out that it's something due to tinymce-vue let me know and I'll re-open it!

**Closed by SimonFc** 2019-07-15 14:54 UTC
