### ISSUE TITLE
V6 error in build - No code files created when installing the package

### ISSUE THREAD

**Issue by ThomasBerneHCSE** [tinymce/tinymce-vue#418] opened 2024-06-10 07:51 UTC
**What is the current behavior?**

There is no code in the package when installed : https://codesandbox.io/p/devbox/5q6jv2?migrateFrom=fg73hj

![image](https://github.com/tinymce/tinymce-vue/assets/129750331/0c227b53-f898-454e-ad1f-7cb950bf8473)

**What is the expected behavior?**

There should be code in this folder. The `lib/cjs/main/ts/index.js` and `lib/es2015/main/ts/index.js` don't exist.

**Comment by ThomasBerneHCSE** [comment] 2024-06-10 07:52
I created a duplicate of this issue https://github.com/tinymce/tinymce-vue/issues/417 but with a reproduction.

**Comment by sebastianvitterso** [comment] 2024-06-10 09:21
Might be just as good to put this reproduction in a comment in #417?

**Comment by danoaky-tiny** [comment] 2024-06-12 03:46
We've identified the issue and are working on a fix. Apologies for the inconvenience.
Duplicate of #417

**Comment by danoaky-tiny** [comment] 2024-06-12 04:34
Please use v6.0.1, this has the built _/lib_.

**Closed by danoaky-tiny** 2024-06-12 04:34 UTC
Labels: bug, duplicate
