### ISSUE TITLE
unrecognized expression

### ISSUE THREAD

**Issue by UrbanRogue1** [tinymce/tinymce-vue#120] opened 2020-02-04 20:56 UTC
I am following the instructions to install tinymce-vue and when I insert the component with my api-key I am getting nothing an empty textarea.  
`<textarea data-v-657af474="" id="tiny-vue_5627879202Tue Feb 04 2020 16:18:16 GMT-0500 (Eastern Standard Time)" data-v-4bc16661="" style=""></textarea>`
Note I am using NUXT

What I get is this in the console

tinymce.min.js:9 Uncaught Error: Syntax error, unrecognized expression: #tiny-vue_5627879202Tue Feb 04 2020 16:18:16 GMT-0500 (Eastern Standard Time)

What I do see is this error seems to be the exact same as what is being set as the ID of the textarea

What I put in the template is
`<editor
              apiKey="MYKEY"
              initialValue="<p>This is the initial content of the editor</p>"
              :init="{
                plugins: [
                  'advlist autolink lists link image charmap print preview anchor',
                  'searchreplace visualblocks code fullscreen',
                  'insertdatetime media table paste code help wordcount'
                ]
              }"
            ></editor>`

I get the same error when I just put in 
`<editor></editor>`

What I see in the <head>
`<script referrerpolicy="origin" type="application/javascript" id="tiny-script_3366733491Tue Feb 04 2020 15:50:15 GMT-0500 (Eastern Standard Time)" src="https://cdn.tiny.cloud/1/LONGKEYHERE/tinymce/5/tinymce.min.js"></script>`

Using "@tinymce/tinymce-vue": "^3.1.0" in Chrome

**Comment by UrbanRogue1** [comment] 2020-02-04 21:26
Seems adding
id="testing1234" ( or some unique ID)
it seems to work.  

Perhaps there is a bug in the creation of the ID if it is not set?

**Comment by SimonFc** [comment] 2020-02-05 09:18
Space isn't a valid character for id-attributes. Does removing the spaces fix the issue for you?

**Comment by SimonFc** [comment] 2020-02-05 09:51
tinymce-vue will use `Date.now()` as part of the step for creation of a random id, although space isn't a valid character for id-attributes so I think something went wrong there. I'm not familliar with NUXT but it appears to be server rendered? Perhaps whatever implementation of Date being used will return what you got instead of just a number ("123456") which it should. Just to verify my suspicions, what do you get when you log/render/execute `Date.now()` somewhere in your NUXT environment?

**Comment by UrbanRogue1** [comment] 2020-02-05 13:37
with Date.now() I get Wed Feb 05 2020 08:35:35 GMT-0500 (Eastern Standard Time)
with new Date().getTime() I get 1580909735422

**Comment by SimonFc** [comment] 2020-02-05 16:08
Thanks! It is as I suspected. The issue isn't actually one with tinymce-vue but rather with Nuxt.js (or with whatever server rendering system they're using) so if you feel like it you could report it to them as well. In any case I'll change the id generation logic in tinymce-vue to use `new Date().getTime()` as this actually is what our other TinyMCE wrappers are doing anyway (we support React and Angular as well)

**Comment by UrbanRogue1** [comment] 2020-02-05 16:10
Awesome. Thanks.  I will look in to reporting the date issue with Nuxt as well.
Im sure this will remove some confusion for any Nuxt users :)

**Comment by SimonFc** [comment] 2020-02-06 10:03
@UrbanRogue1 I took a closer look at Nuxt.js and as it is I can't seem to be able to replicate the behavior you have described. I used version 2.12.0 of create-nuxt-app to get started, while using version 10.16.0 of Node.js.

Is it possible for you to describe how you set up Nuxt.js? And what versions are you using? Thanks!

**Comment by UrbanRogue1** [comment] 2020-02-06 14:05
Currently on Node 10.15.3 and running Nuxt 2.11.0.

**Comment by UrbanRogue1** [comment] 2020-02-06 14:08
NPM to install all the packages i have in package.json.  another Developer who is no longer with us set it all up initially

**Comment by SimonFc** [comment] 2020-02-06 16:10
Very strange. Date.now() in Node 10.15.3 returns a value in milliseconds, as expected. Could it perhaps be that you have something that's polyfills Date? Is it possible for you to set up a clean project with the same issue?

**Comment by UrbanRogue1** [comment] 2020-02-06 16:12
I will try to find some time to set up a new project today or tomorrow to see if I can replicate.

I will also try to scan through all his code and see if something is set up to polyfill the date.

**Comment by SimonFc** [comment] 2020-02-25 12:50
@UrbanRogue1 Have you been able to replicate the issue? If not I'm going to assume that this is something specific to your environment, such as a polyfill being added.

**Comment by UrbanRogue1** [comment] 2020-02-25 13:33
Cant seems to replicate it on a fresh install.  I have to track down what package this past Dev used that is messing it up.

**Comment by SimonFc** [comment] 2020-02-25 14:16
Alright, since this isn't an issue due to tinymce-vue nor something which seems to be a common thing in the Vue ecosystem, I'll close this. You can still comment here if you find that this isn't the case

**Closed by SimonFc** 2020-02-25 14:16 UTC
Labels: status: escalated
