### ISSUE TITLE
onShow event not working

### ISSUE THREAD

**Issue by fabioebner** [tinymce/tinymce-vue#91] opened 2019-06-08 14:19 UTC
**What is the current behavior?**
The event onShow are not executing

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
https://codesandbox.io/embed/tinymcevue-t9cdc

**What is the expected behavior?**
When the editor show at the screen he should execute the onShow event

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-vue`?**
  "dependencies": {
    "@tinymce/tinymce-vue": "2.0.0",
    "vue": "^2.5.22"
  }

**Comment by SimonFc** [comment] 2019-07-15 14:50
This seems to just be a mix-up of events, easily happens. What you're looking for is the `onInit` event.

The `onShow` event fires after the [show](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#show) method has been executed on the editor and the `onHide` event fires after the [hide](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#hide) method has been executed.

Let me know if you got any questions! Closing this now since it's not a bug

**Closed by SimonFc** 2019-07-15 14:50 UTC
